### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by romanrehacek** [codercom/code-server#352] opened 2019-03-27 07:37 UTC
- `code-server` version: 1.408-vsc1.32.0-linux-x64
- OS Version: Ubuntu 18.04.2 LTS

## Description

I get `Segmentation fault (core dumped)` on new release. Older release works fine.

```
roman@dev:~/code-server$ cd code-server-1.32.0-310-linux-x64/
roman@dev:~/code-server/code-server-1.32.0-310-linux-x64$ ./code-server ${PWD} -p 3300 --allow-http --no-auth
INFO  code-server v1.32.0-310
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/roman/.local/share/code-server","working-dir":"/home/roman/code-server/code-server-1.32.0-310-linux-x64","log-dir":"/home/roman/.cache/code-server/logs/20190327073305084"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"0.0.0.0","port":3300}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
WARN  Launched without authentication.
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:3300/
INFO   
INFO  Connected to shared process
^C
roman@dev:~/code-server/code-server-1.32.0-310-linux-x64$ cd ../code-server1.408-vsc1.32.0-linux-x64/
roman@dev:~/code-server/code-server1.408-vsc1.32.0-linux-x64$ ./code-server ${PWD} -p 3300 --allow-http --no-auth
Segmentation fault (core dumped)

```

**Comment by ymmt2005** [comment] 2019-03-27 08:53
Duplicate of #346

**Closed** 2019-03-27 09:34 UTC
Labels: bug
