### ISSUE TITLE
preference doesn't save

### ISSUE THREAD

**Issue by shi-yan** [codercom/code-server#321] opened 2019-03-23 00:09 UTC
- `code-server` version: tot
- OS Version: ubuntu 18.04 in docker and on host

## Description

I tried to config the shortcut, and it doesn't save. if I refresh the browser, the old default preference comes back.

**Comment by vimota** [comment] 2019-03-24 04:31
Does it work if you do something like `docker run -t -p 127.0.0.1:8443:8443 -v "$HOME/path/to/project:/root/project" -v "/$HOME/.coder:/root/.local"  codercom/code-server --allow-http --no-auth` ? The preferences should be saved in /root/.local/ which will be stored in your /$HOME/.coder, and preserved between sessions.

**Comment by sr229** [comment] 2019-03-26 03:18
Can't reproduce this issue. I don't think this persists anymore.

**Comment by shi-yan** [comment] 2019-03-26 18:48
![Screenshot from 2019-03-26 11-44-36](https://user-images.githubusercontent.com/326807/55024794-d1929000-4fbc-11e9-8faf-351fa950ecc8.png)

This is still happening to me. the specific config I need to change is keyboard binding. The result of the change should be in keybindings.json, which I verified is there with the right content.

but if I close the browser tab and reconnect, the keybindings won't change at all. it doesn't seem to load the json file.

**Comment by sr229** [comment] 2019-03-27 12:07
So this is only for keybindings I presume? Other preferences saves fine

**Comment by RyanK1m** [comment] 2019-03-28 19:04
Same here.
Custom keybinding works properly when you first customize them. 
When reload, default keybinding overwrites it. 
If you open up custom keybindings again and just save it, custom keybinding works again.

Other preferences save just fine.

**Comment by weikinhuang** [comment] 2019-03-29 00:32
same issue here from me https://github.com/codercom/code-server/issues/150

**Comment by sr229** [comment] 2019-03-29 08:52
This might be a confirmed bug, I can confirm this on CoreOS

**Comment by kylecarbs** [comment] 2019-04-18 01:04
Duplicate of https://github.com/codercom/code-server/issues/321

**Closed by kylecarbs** 2019-04-18 01:04 UTC
Labels: bug
