### ISSUE TITLE
1.408 doesn't work with --cert args

### ISSUE THREAD

**Issue by mentz** [codercom/code-server#378] opened 2019-03-29 13:21 UTC
- `code-server` version: `1.408-vsc1.32.0`
- OS Version: Ubuntu Server 18.04 LTS (VM on Hyper-V)

## Description

Trying to run `code-server` with `--cert` and `--cert-key` arguments causes application to exit issuing error `EEXIST: file already exists, mkdir '<cert-path>'`.

## Steps to Reproduce

1. Acquire certificates for HTTPS operation
2. Try to run code-server with certificates, e.g. `./code-server --cert fullchain.pem --cert-key privkey.pem`

## Error shown

Below is a complete example of the error I am getting when running code-server following above steps:

```text
lucas@u1804-coder:~/code-server1.408-vsc1.32.0-linux-x64$ ./code-server --cert fullchain.pem --cert-key privkey.pem
ERROR { Error: EEXIST: file already exists, mkdir '/home/lucas/code-server1.408-vsc1.32.0-linux-x64/fullchain.pem'
  [stack]: 'Error: EEXIST: file already exists, mkdir \'/home/lucas/code-server1.408-vsc1.32.0-linux-x64/fullchain.pem\'',
  [message]: 'EEXIST: file already exists, mkdir \'/home/lucas/code-server1.408-vsc1.32.0-linux-x64/fullchain.pem\'',
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/home/lucas/code-server1.408-vsc1.32.0-linux-x64/fullchain.pem' }
free(): invalid pointer
Aborted (core dumped)
```

## Previous versions

This error does not happen on previous `code-server` version `1.32.0-310`.

**Comment by kylecarbs** [comment] 2019-03-29 17:20
Will fix. Thanks for the report!

**Comment by mcp352** [comment] 2019-03-29 19:17
Exact same issue. Is there an easy workaround? Thanks for posting Mentz.

**Comment by mentz** [comment] 2019-03-29 21:43
The "workaround" I'm using is reverting to version `1.32.0-310`.

**Comment by kmahyyg** [comment] 2019-03-31 17:19
same issue as #351

**Comment by mentz** [comment] 2019-03-31 18:23
Sorry, I didn't think it was a duplicate. Seeing that it's a different error I thought it would be better to open a new issue for this one.

**Comment by cy91244** [comment] 2019-04-01 02:49
Got exact same error too, another workaround for now might be using reverse proxy like nginx to perform ssl transmission.

**Comment by code-asher** [comment] 2019-04-01 15:48
Did some testing and it looks like what fixed https://github.com/codercom/code-server/issues/351 also fixed this one (that fix hasn't been released yet though). The different arguments caused a different error message, but the root cause was the same.

**Comment by XiaolongMeng** [comment] 2019-04-04 06:09
same error, waiting to be fixed

**Comment by kylecarbs** [comment] 2019-04-04 14:18
Fixed with [the latest release](https://github.com/codercom/code-server/releases/tag/1.604-vsc1.32.0)!

**Closed by kylecarbs** 2019-04-04 14:18 UTC
Labels: bug
