### ISSUE TITLE
Moving file to another folder throws console error

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#434] opened 2019-04-04 21:51 UTC
- `code-server` version: v1.604-vsc1.32.0
- OS Version: 10.14.4 (18E226)

## Description
Dragging and dropping one file to another results in an error.

`Error: Cannot parse time: [object Object]`

## Steps to Reproduce
1. Click and drag a file from one folder to another

**Comment by Multishifties** [comment] 2019-04-04 21:52
Duplicate of https://github.com/codercom/code-server/issues/253

**Closed** 2019-04-04 21:52 UTC
Labels: bug
