### ISSUE TITLE
Can't open a workspace

### ISSUE THREAD

**Issue by romanrehacek** [codercom/code-server#507] opened 2019-04-17 06:22 UTC
- `code-server` version: 1.621
- OS Version: ubuntu 18

## Description

When I use latest docker image, I can't open a workspace or add folder to workspace. Nothing happend. No refresh, no error, no new added folder in exploler. Mounted folder works.
```
docker run -it -p 3400:8443 --name test -v "/var/www:/home/coder/project" codercom/code-server --allow-http --no-auth
```

But when I try older docker image, it works.
```
docker run -it -p 3400:8443 --name test -v "/var/www:/home/coder/project" codercom/code-server:1.604-vsc1.32.0 --allow-http --no-auth
```

**Comment by foresthoffman** [comment] 2019-04-17 15:29
This is a duplicate of https://github.com/codercom/code-server/issues/490, we'll track the issue there. Thank you!

**Closed by foresthoffman** 2019-04-17 15:29 UTC
Labels: bug
