### ISSUE TITLE
Crash on Debian 8

### ISSUE THREAD

**Issue by RookieZoe** [codercom/code-server#67] opened 2019-03-07 05:20 UTC
- `code-server` version: 1.31.1-100
- OS Version: debian 8

```bash
$ uname -a
Linux iZ28iwnpx2bZ 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

$ cat /etc/debian_version
8.11
```

#### Steps to Reproduce

error message:
```bash
$ ./code-server -d /home/zoe/codes/vscode-workdir -h 127.0.0.1 -p 60443 --allow-http
INFO  code-server v1.31.1-100
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/zoe/codes/vscode-workdir","working-dir":"/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64","log-dir":"/home/zoe/codes/vscode-workdir/logs/20190307051426515"}
INFO  Starting shared process [1/5]...
INFO  Starting webserver... {"host":"127.0.0.1","port":60443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
INFO
INFO  Password: e9eb8d0a4d8c913247d49cc0
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:60443/
INFO
INFO  Connected to shared process
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/home/zoe/codes/vscode-workdir/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/home/zoe/codes/vscode-workdir/Backups/workspaces.json'\n    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64/code-server:468:27371), <anonymous>:71445:31)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)\n"}
INFO  WebSocket opened / {"client":1,"ip":"127.0.0.1"}
INFO  Created data directory
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn [as _spawn] (child_process.js:502:9)
    at t.async (/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64/code-server:716:35021)
    at e.exports (/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64/code-server:716:34522)
    at e (/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/home/zoe/codes/vscode-workdir/code-server-1.31.1-100-linux-x64/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

**Comment by kylecarbs** [comment] 2019-03-07 06:24
Seems like you're out of memory.

**Comment by chuyik** [comment] 2019-03-07 08:00
Similar crash on centos 7 machine with 1 cpu core and 2G ram:

```
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
INFO  Connected to shared process

ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'

Error: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'
    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/root/installers/code-server-1.31.0-20-x86_64-linux/code-server:468:27371), <anonymous>:71434:31)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
"}
```

And the process hangs here, no `spawn` like error shows up.
So I doubt that it may related to other issues rather than memory.

**Comment by wogong** [comment] 2019-03-07 08:23
Exactly the same crash on ubuntu 16.04 machine with 8 cpu core and 48G ram, this might not be caused by out of memory.

**Comment by jerodev** [comment] 2019-03-07 08:23
Same problem on Debian 9.

```
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO   
INFO  Starting shared process [1/5]...
INFO  Connected to shared process
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/home/jerodev/.code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/home/jerodev/.code-server/Backups/workspaces.json'\n    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/home/jerodev/codercom/code-server:468:27371), <anonymous>:71445:31)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)\n"}
```

**Comment by jerodev** [comment] 2019-03-07 10:55
I've got it working now by creating `Backups/workspaces.json` manually in the workdir directory with the following content:

    {"rootWorkspaces":[],"folderURIWorkspaces":[],"emptyWorkspaceInfos":[],"emptyWorkspaces":[]}

And then creating the folder `{workdir}/User/workspaceStorage`.

**Comment by chuyik** [comment] 2019-03-07 11:14
@jerodev This works for me, thanks!
But from my experience, it should be `{data-dir}/User/workspaceStorage`

**Comment by kylecarbs** [comment] 2019-03-07 17:30
Interesting. Will investigate.

**Comment by zk-g** [comment] 2019-03-08 18:05
Posting mine too maybe it help.
Running it as Root

INFO  Started (click the link below to open):
INFO  http://localhost:443/
INFO
INFO  Starting shared process [1/5]...
INFO  Connected to shared process
INFO  WebSocket opened / {"client":1,"ip":"XXXXXXXX"}
INFO  Created data directory
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn [as _spawn] (child_process.js:502:9)
    at t.async (/root/code-server/code-server:716:35021)
    at e.exports (/root/code-server/code-server:716:34522)
    at e (/root/code-server/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/root/code-server/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by NGTmeaty** [comment] 2019-03-08 18:06
How much memory do you have available when getting this error?

**Comment by zk-g** [comment] 2019-03-08 18:08
With a 2gb vps, 1 gb remain avaible and code-server process still working, while the interface return ERR_CONNECTION_REFUSED.

**Comment by NiklasMerz** [comment] 2019-03-08 18:11
I get no error while starting it on Ubuntu 18.04 but the browser loads endlessly.

**Comment by NGTmeaty** [comment] 2019-03-08 18:12
Which version are you running on @NiklasMerz ?

**Comment by zk-g** [comment] 2019-03-08 18:14
When I look at process running with htop, code-server appear pretty strange, the commands calling code-server are like ∞ length.

**Comment by kylecarbs** [comment] 2019-03-08 18:15
Could you post a snippet of one @zk-g ?

**Comment by zk-g** [comment] 2019-03-08 18:17
I m figuring out how to copy the full htop command string, whit Shift I just can copy what I see on screen

**Comment by NiklasMerz** [comment] 2019-03-08 18:25
>Which version are you running on @NiklasMerz ?

The latest Version of Code-Server.

Is there any kind of verbose mode?

**Comment by zk-g** [comment] 2019-03-08 18:27
I didn't figure out how to copy the full string I ll just post the first part and a middle part
` /root/code-server/code-server --bootstrap-fork vs/workbench/services/extensions/node/extensionHostProcess --args ["--type=extensionHost"] --env {"   ":"/root/code-server/code-server"STY":"32514.code-server","SSH_CONNECTION":"XXX.XXX.XXX.XX 50263 XXX.XXX.XXX.XX 22","LANG":"en_US.UTF-8","OLDPWD":"/root","USER":"root","PWD":"E[19~:k9=\\E[20~:k;=\\E[21~:F1=\\E[23~:F2=\\E[24~:\\\n\t:F3=\\E[1;2P:F4=\\E[1;2Q:F5=\\E[1;2R:F6=\\E[1;2S:\\\n\t:F7=\\E[15;2~:F8=\\E[17;2~:F9=\\E[18;2~:FA=\\E[19;2~:\\\n\t:FB=\\E[20;` --> then it keep like that

**Comment by NGTmeaty** [comment] 2019-03-08 18:27
I wonder if this could be a Screen issue? Could you try running it without screen?

**Comment by kylecarbs** [comment] 2019-03-08 18:27
@NiklasMerz you can export `LOG_LEVEL` to `debug` and it'll provide verbose output.

**Comment by kylecarbs** [comment] 2019-03-08 18:28
@zk-g that command appears to be _mostly_ correct. The PWD looks odd. Does it work for you?

**Comment by bdodroid** [comment] 2019-03-08 18:34
I get this exact same error only when trying to run Debug->Start Debugging from the VScode menu for a node.js project.

**Comment by zk-g** [comment] 2019-03-08 18:36
Now I killed the screen but when running htop I still can see all code-server process running.
I started code-server without the screen with the command
`./code-server --password=XXX --cert /etc/letsencrypt/live/XXX/cert.pem --cert-key /etc/letsencrypt/live/XXX/privkey.pem -d /home/vscode -p 443`
and i got the same error:
`Error: spawn ENOMEM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn [as _spawn] (child_process.js:502:9)
    at t.async (/root/code-server/code-server:716:35021)
    at e.exports (/root/code-server/code-server:716:34522)
    at e (/root/code-server/code-server:716:33324)
    at Timeout.c [as _onTimeout] (/root/code-server/code-server:716:33617)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
`
While the interface return the error "Lost connection to socket. Retrying in Xs."

**Comment by NGTmeaty** [comment] 2019-03-08 18:37
@zk-g are you still getting the weird super long code-server in htop?

**Comment by NiklasMerz** [comment] 2019-03-08 18:38
> @NiklasMerz you can export LOG_LEVEL to debug and it'll provide verbose output.

Thanks but still no error. Just a high CPU load and no response in the browser. It is stuck at 

`INFO  Starting shared process [1/5]...`

**Comment by zk-g** [comment] 2019-03-08 18:39
Yes, but for be sure It s not still a screen bug related I ll try restart the vps and I try again

**Comment by zk-g** [comment] 2019-03-09 12:30
Update: After restarting and starting code-server without screen, the htop command seem more 'normal' length, I still get the same usual error `ERROR SHARED stderr` but for now still not crash, CPU load is normal and code-server take around 700 mb of ram.

```

root@xxx:~/code-server# ./code-server --cert /etc/letsencrypt/live/xxx/cert.pem --cert-key /etc/letsencrypt/live/xxx/privkey.pem -d /home/vscode -p 443
INFO  code-server v1.0.0
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/vscode","working-dir":"/root/code-server","log-dir":"/home/vscode/logs/20190309121854195"}
INFO  Starting webserver... {"host":"0.0.0.0","port":443}
INFO
INFO  Password: 4ecDQQlGR7Hb
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:443/
INFO
INFO  Starting shared process [1/5]...
INFO  Connected to shared process
INFO  WebSocket opened / {"client":1,"ip":"xxx"}
INFO  Created data directory
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/home/vscode/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/home/vscode/Backups/workspaces.json'\n    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/root/code-server/code-server:468:27371), <anonymous>:71434:31)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)\n"}
INFO  WebSocket closed / {"client":1,"code":1001}
INFO  WebSocket opened / {"client":2,"ip":"xxx"}
INFO  Created data directory


```

**Comment by kylecarbs** [comment] 2019-04-04 14:34
Likely helped by [the latest release](https://github.com/codercom/code-server/releases/tag/1.604-vsc1.32.0). Closing in favor of #169.

**Closed by kylecarbs** 2019-04-04 14:34 UTC
Labels: bug, needs-investigation
