### ISSUE TITLE
Debug Python doesn't work 

### ISSUE THREAD

**Issue by Technik-J** [codercom/code-server#276] opened 2019-03-17 19:52 UTC
- `code-server` version:
```
server/1.32.0-282 linux-x64 node-v8.15.0
```
- OS Version: 
```
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
```

## Description
Debug for Python doesn't work. Stays in a loop forever.

![Screenshot from 2019-03-18 00-44-12](https://user-images.githubusercontent.com/17809291/54497046-e9f90f80-4917-11e9-955e-09cf4b8e6b8f.png)
## Steps to Reproduce

1. Debug python file.

**Comment by davefinster** [comment] 2019-03-17 20:31
This seems similar to #210

**Comment by sr229** [comment] 2019-03-18 16:17
Confirmed duplicate of Issue #210.

**Comment by foresthoffman** [comment] 2019-03-18 16:21
Closing in favor of #210, we'll track the issue there.

**Closed by foresthoffman** 2019-03-18 16:21 UTC
Labels: bug
