### ISSUE TITLE
Stuck starting shared process

### ISSUE THREAD

**Issue by prestonvanloon** [codercom/code-server#153] opened 2019-03-08 23:22 UTC
- `code-server` version: v1.31.1
- OS Version: ubuntu

#### Steps to Reproduce

```
code-server --allow-http --no-auth .
INFO  code-server v1.31.1-100
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/home/preston/.code-server","working-dir":".","log-dir":"/home/preston/.code-server/logs/20190308231846670"}
INFO  Starting webserver... {"host":"0.0.0.0","port":8443}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
WARN  Launched without authentication.
INFO
INFO  Started (click the link below to open):
INFO  http://localhost:8443/
INFO
INFO  Starting shared process [1/5]...
```

It sits here forever.

**Comment by yzwduck** [comment] 2019-03-09 11:18
Same problem for Archlinux, it stucks here, eats up memory slowly and finally OOM crashes (in a few hours).
Reproduced on a fresh installed Archlinux with code-server v1.31.1-100 from GitHub release.

**Comment by sr229** [comment] 2019-03-11 07:25
@prestonvanloon, Hey there, you need `net-tools` to make code-server work. This is a hard dependency, so you must install it.

**Comment by xuthus5** [comment] 2019-03-12 03:58
> @prestonvanloon, Hey there, you need `net-tools` to make code-server work. This is a hard dependency, so you must install it.
> 
> Mark this closed as this is already solved by #44.

I tested that under CentOS 7, the problem persisted even if packages with net-tools were installed.

**Comment by xuthus5** [comment] 2019-03-12 05:15
I tested that under CentOS 7, the problem persisted even if packages with net-tools were installed.Because GCC and dependency library versions are too low, high versions are required. The problem can be solved by recompiling and installing GCC above version 5(The highest version is GCC is 4.8 on my machine)

**Comment by sr229** [comment] 2019-03-12 16:18
I don't think you should be running it on CentOS since its intended for environments with dependencies that dates back to bygone eras.

**Comment by prestonvanloon** [comment] 2019-03-12 20:26
@sr229, I wouldn't consider this issue solved until it logs some error to tell the user that they don't have `net-tools` installed. 

I am unblocked by installed `net-tools` via apt-get. Thanks

**Comment by coadler** [comment] 2019-03-12 20:27
I agree, we should definitely give some sort of indication

cc. @coderasher

**Comment by code-asher** [comment] 2019-03-25 23:55
Should be fixed with https://github.com/codercom/code-server/commit/d16c6aeb30004e2862012dcd75592c27095996ba.

**Closed** 2019-04-19 16:49 UTC
