### ISSUE TITLE
Find a better way to implement the extensions

### ISSUE THREAD

**Issue by zk-g** [codercom/code-server#81] opened 2019-03-07 12:51 UTC
Actually the are just few extensions of the marketplace, specially I find essential this extensions:

- Bookmarks
- Bracket Pair Colorizer 2  
- Code Runner
- GitLens and all github related
- The java extension pack
- Debug extensions
- Setting Sync
- IntelliCode
(I know some are already available)  

_____

Adding a full extensions support and a multi-user function (maybe also with a permission system where the owner can create new users with different permission, like r&w or just read) could really make this the best cloud "ide" and  valid alternative to a local ide. I really hope this functions will be implemented. 
Thanks for your work

**Comment by nhooyr** [comment] 2019-03-08 17:14
Could you elaborate on what exactly you want? This issue is unclear.

**Comment by NGTmeaty** [comment] 2019-03-08 17:16
I believe he's requesting more addons in our marketplace and partially asking for full marketplace extensions? With a request for multiple users and a permissions system?

**Comment by zk-g** [comment] 2019-03-08 17:29
Last part was just a personal note.
Essentially what I asked is to get all the extensions available in the VScode marketplace into Code Server, in the case that is not possible I had made a list of the extensions I would like to have.

**Comment by NGTmeaty** [comment] 2019-03-08 17:32
Thanks for the clarification. I'll check into these for you, but just for reference, we can only get open-source packages on the "Coder" extensions shop due to terms issue with the official VSCode extensions shop.

**Comment by nhooyr** [comment] 2019-03-08 17:55
Duplicate of #30 and #33

**Closed by nhooyr** 2019-03-08 17:55 UTC
Labels: waiting-for-info
