### ISSUE TITLE
Search in folder <-- now working

### ISSUE THREAD

**Issue by peterremote1980** [codercom/code-server#438] opened 2019-04-05 15:45 UTC
Hi
    "Search in folder" not working, "Go to file", also nothing there.
thanks
From Peter

**Comment by kylecarbs** [comment] 2019-04-05 17:11
Will fix.

**Comment by andreimc** [comment] 2019-04-06 04:20
Duplicate of https://github.com/codercom/code-server/issues/392

**Comment by kylecarbs** [comment] 2019-04-08 16:42
Fixed with the [latest pre-release](https://github.com/codercom/code-server/releases/tag/1.696-vsc1.33.0).

**Closed by kylecarbs** 2019-04-08 16:42 UTC
Labels: bug
