### ISSUE TITLE
Python can run directly in the terminal, but can't be debugged with F5

### ISSUE THREAD

**Issue by JavanTang** [codercom/code-server#301] opened 2019-03-20 06:29 UTC
I just saw #210 in the issue, but I still haven't modified the problem. When I debugged it, it didn't report an error, but it didn't respond. When I repeatedly pressed F5 for debugging, it would say that debugging already exists.

**Comment by JavanTang** [comment] 2019-03-20 08:17
I added the cuda environment to the original Docker base. I don't know if it is affected by this, but I will also have this effect by running the docker run command in the readme.
The docker I made is public. The command is: docker pull registry.cn-hangzhou.aliyuncs.com/test_tzf/test:0.1.4

**Comment by kylecarbs** [comment] 2019-03-20 13:50
There are still some issues with debugging from the docker container that we'll need to fix. Looking into this now.

**Comment by Multishifties** [comment] 2019-03-20 18:08
Possible duplicate of https://github.com/codercom/code-server/issues/210 ?

**Comment by kylecarbs** [comment] 2019-03-27 02:34
Fixed with the [latest release](https://github.com/codercom/code-server/releases/tag/1.408-vsc1.32.0).

**Closed by kylecarbs** 2019-03-27 02:34 UTC
Labels: bug
