### ISSUE TITLE
Getting a Black Screen 

### ISSUE THREAD

**Issue by DheerajKN** [codercom/code-server#125] opened 2019-03-08 07:39 UTC
#### Description
Initially I created a Linux VM in Azure and used wget to download the tar.gz file of code-server and ran `./code-server <empty directory>`

Everything was running fine and then I got this error

`ERROR SHARED stderr {"data":"Uncaught Exception:  Error: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'\n\nError: ENOENT: no such file or directory, open '/root/.code-server/Backups/workspaces.json'\n    at Timeout.eval [as _onTimeout] (eval at exports.requireModule (/home/knd/Coder-codeServer/code-server-1.31.1-100-linux-x64/code-server:468:27371), <anonymous>:71445:31)\n    at ontimeout (timers.js:475:11)\n    at tryOnTimeout (timers.js:310:5)\n    at Timer.listOnTimeout (timers.js:270:5)\n"}`

But even after encountering so I went to localhost:8443 and under Advanced accept the unsafe way which displayed password which I copied from my terminal, there is a black screen that is being rendered.

#### Related Issues
-> What did I do wrong??
-> Why I am getting a black screen??
-> What is the Error, and how to solve it??

**Comment by ICEFIR** [comment] 2019-03-08 07:57
That error is irrelevant... at least for now
The page render could take a while to load, so I guess just wait a while, and keep monitoring the console output to see what's going on?

**Comment by kylecarbs** [comment] 2019-03-08 16:21
Try also clearing your cache. There's a problem with the unauthed->authed screen with caching.

**Comment by NGTmeaty** [comment] 2019-03-08 16:59
Duplicate of #121 ?

**Comment by nhooyr** [comment] 2019-03-08 16:59
Seems to be the same as #121

**Comment by kylecarbs** [comment] 2019-03-08 17:01
Continue discussion in https://github.com/codercom/code-server/issues/121

**Closed by kylecarbs** 2019-03-08 17:01 UTC
Labels: waiting-for-info

**Comment by jrpub** [comment] 2019-03-11 19:19
I had also the black screen.  To solve it, do not use relative path for your project when loading code-server, put the absolute path to your project.

It solves the black screen, but I still have the #121 which does not prevent vscode to work.

**Comment by renerocksai** [comment] 2019-03-13 13:04
> I had also the black screen. To solve it, do not use relative path for your project when loading code-server, put the absolute path to your project.
> 
> It solves the black screen, but I still have the #121 which does not prevent vscode to work.

I cannot second that. I still get the black screen, even with an absolute project path, and: this does prevent vscode to work since the screen becomes unresponsive and eventually totally dark (and unresponsive)

**Comment by renerocksai** [comment] 2019-03-13 13:31
> > I had also the black screen. To solve it, do not use relative path for your project when loading code-server, put the absolute path to your project.
> > It solves the black screen, but I still have the #121 which does not prevent vscode to work.
> 
> I cannot second that. I still get the black screen, even with an absolute project path, and: this does prevent vscode to work since the screen becomes unresponsive and eventually totally dark (and unresponsive)

Some more info: it actually started to work ONCE after like ten minutes -- on a box with 64GB RAM, 48 cores. It locked up after double-clicking a file to open it. After that the UI locks up, eventually it goes blank entirely. Then, 15 minutes later, it suddenly works -- UNTIL you hit reload in the browser. I am trying to reproduce but unfortunately, after opening a file it is still stuck, has been for ages now.

**Comment by renerocksai** [comment] 2019-03-13 14:14
> > > I had also the black screen. To solve it, do not use relative path for your project when loading code-server, put the absolute path to your project.
> > > It solves the black screen, but I still have the #121 which does not prevent vscode to work.
> > 
> > 
> > I cannot second that. I still get the black screen, even with an absolute project path, and: this does prevent vscode to work since the screen becomes unresponsive and eventually totally dark (and unresponsive)
> 
> Some more info: it actually started to work ONCE after like ten minutes -- on a box with 64GB RAM, 48 cores. It locked up after double-clicking a file to open it. After that the UI locks up, eventually it goes blank entirely. Then, 15 minutes later, it suddenly works -- UNTIL you hit reload in the browser. I am trying to reproduce but unfortunately, after opening a file it is still stuck, has been for ages now.

OK, this seems to happen only in project folders with many files (thousands). In teeny-weeny src only folders this doesn't happen.

**Comment by kylecarbs** [comment] 2019-03-13 17:19
Interesting. There's actually a VS Code issue open for pegging CPU with the watcher.

**Comment by renerocksai** [comment] 2019-03-14 16:16
> Interesting. There's actually a VS Code issue open for pegging CPU with the watcher.

OK, good to know. However, this behavior does not show when running vscode locally, accessing the project directory over a samba share (or at least it doesn't hog for longer than 1-2s).
